---
title: "Assignment 6"
author: "Sofia Sarak"
format: html
editor: visual
---

Load necessary libraries
```{r}
#| message: false
#| warning: false

# libraries
library(tidyverse)
library(deSolve)
library(here)
library(sensitivity)
```

### 1. Implement Model in R as Differential Equations

```{r}
# forest growth function
source(here("R/dforestgrowth.R"))
```

### 2. Run the Model

Run the model for 300 years using ODE solver and defined parameters
```{r}
# create a sequence of years from 1 to 300
time <- seq(from = 1, to = 300)

# initial forest size 
Cinitial <- 10

# create list of parameters to input into ode
params <- list(K = 250, r = 0.01, g = 2)

# run ode function and save result
res <- ode(y = Cinitial, times = time, func = dforestgrowth, parms = params)

# rename columns for clarity
colnames(res) <- c("time", "dC")
```

### 3. Graph ODE results

```{r}
# plot 
ggplot(as.data.frame(res), aes(time, dC)) +
  geom_point(color= "cornflowerblue") +
  labs(title = "Trajectory with no uncertainty") +
  theme_minimal()
```

### 4. Run a Sobol Global

```{r}
# create wrapper function
c_wrapper <- function(K, r, g, Cinitial, simtimes, odefunc, metricfunc, metricpars) {
  
  # create parameter list
  parms <- list(r = r, K = K, g = g)
  
  # run ode
  result <- ode(y = Cinitial, times = simtimes, func = odefunc, parms = params, method="euler")
  
  # results as a data frame
  result = data.frame(time=result[,1], dC=result[,2])
  
  # compute metrics
  metrics <- metricfunc(as.data.frame(result), metricpars$thresh)
  return(metrics)
}
```

```{r}
# test with specific values
# test with specific r and K values (r=0.01, K=150)
# set out threshold 
metricpars = list(thresh=100)
p_wrapper(
  r = 0.01, K = 150, Pinitial = 3, simtimes = seq(from = 1, to = 10),
  odefunc = dpopgrowth, metricfunc = compute_pop_metrics, metricpars = metricpars
)

# try with first row of our Sobol parameters
p_wrapper(r=sens_P$X[1,"r"], K=sens_P$X[1,"K"],
          Pinitial=10, simtimes=simtimes, odefunc=dpopgrowth,
          metricfunc=compute_pop_metrics, metricpars)
```

```{r}
# now use pmap as we did before

allresults <- as.data.frame(sens_P$X) %>% pmap(p_wrapper, Pinitial = Pinitial, simtimes = simtimes, odefunc = dpopgrowth, metricfunc = compute_pop_metrics, metricpars=list(thresh=100))

# extract out results from pmap into a data frame
allres <- allresults %>% map_dfr(`[`, c("maxpop", "threshyear"))

# do a quick summary to get a sense of the range
summary(allres)
# create boxplots of our two metrics for all parameters - use facet wrap since population and year are different y-axis
tmp <- allres %>% pivot_longer(cols = everything(), names_to = "metric", values_to = "value")
ggplot(tmp, aes(metric, value)) +
  geom_boxplot()+facet_wrap(~metric, scales="free")
```

