---
title: "Almond Profit"
author: "Sofia Sarak"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false

# Load necessary libraries
library(tidyverse)
library(here)
library(janitor)

# Read in data
climate <- read_table(here("week 3/clim.txt")) %>% 
  clean_names()
```

```{r}
source(here("alm_yield.R"))
```

```{r}
yield <- alm_yield(climate)

price_lb <- 1.99
price_ton <- price_lb * 2000

revenue <- price_ton * yield

cost_acre <- 3029

profit <- revenue - cost_acre

profit
```

```{r}
alm_profit <- function(price_lb, cost_acre, climate_data){
  
## Creating alm_yield function
  alm_yield <- function(climate_data){
  
  # Find mean minimum temperature in February of each year
  climate_month <- climate_data %>% 
  filter(month == 2) %>% 
  group_by(year) %>% 
  summarize(min_temp_feb = mean(tmin_c))
  
  # Find total precipitation in January of each year 
  precip_month <- climate_data %>% 
    filter(month == 1) %>% 
    group_by(year) %>% 
    summarize(precip_sum_jan = sum(precip))
  
  # Extract necessary variables from respective dfs
  tmin_feb <- climate_month$min_temp_feb
  prec_jan <- precip_month$precip_sum_jan
  
  # Apply formula to variables
  yield <- (-0.015 * tmin_feb) - (0.0046 * (tmin_feb)^2) - (0.07 * prec_jan) + (0.0043 * (prec_jan)^2) + 0.28
  
}
  
## Calculating profit
  # Calculate price per ton
  price_ton <- price_lb * 2000
  
  # Calculate revenue
  revenue <- price_ton * yield
  
  # Calculate final profit
  profit <- revenue - cost_acre
  
  return(data.frame(yield = yield, profit = profit, price_lb = price_lb, cost_acre = cost_acre))
}
```

```{r}
alm_profit(1.99, 3029, climate)
```

```{r}
price_lb <- seq(1, 3, by = 0.1)
```


```{r}
df <- map_df(.x = price_lb, ~alm_profit(.x, cost_acre = 3029, climate))
```

```{r}
ggplot(df, aes(x = factor(price_lb), y = profit)) +
  geom_boxplot()
```
```{r}
ggplot(df, aes(x = factor(price_lb), y = profit)) +
  geom_boxplot(outlier.shape = NA) +
  ylim(-3500, 3500)
```

